baseurl = "/"
languageCode = "es-Es"
#title = "MoonCafe-1201"

[params]
  #description = "An example website for restaurants built by [@eliwilliamson](https://github.com/eliwilliamson) using [Victor Hugo](https://github.com/netlify/victor-hugo)."
  logo="/img/index.png"
  vidmp4 = "/videos/CoffeeCup.mp4"
  
[[menu.main]]
    name = "Nosotros"
    url  = "/nosotros"
    weight = 1

[[menu.main]]
    name = "Menu"
    url  = "/menu"
    weight = 2
[[menu.main]]
    name = "Pedidos"
    url  = "/pedidos"
    weight = 2
[[menu.main]]
    name = "Contacto"
    url  = "/contacto"
    weight = 3
