baseurl = "/"
languageCode = "es-Es"
title = "Moon Cafe-1201"


[params]
  description = "Moon cafe San Marcos, Guatemala"
  itsky = "https://facebook.com/itskyapps"
  logo="/img/index.png"
  vidmp4 = "/videos/CoffeeCup.mp4"
  
[[menu.main]]
    name = "Nosotros"
    url  = "/nosotros"
    weight = 1

[[menu.main]]
    name = "Menu"
    url  = "/menu"
    weight = 2
[[menu.main]]
    name = "Pedidos"
    url  = "/pedidos"
    weight = 2
[[menu.main]]
    name = "Contacto"
    url  = "/contacto"
    weight = 3
